- name: deploy2nekoweb
  # You may pin to the exact commit or the version.
  # uses: indiefellas/deploy2nekoweb@143fee495be60339b53595023bab68794ca535fa
  uses: indiefellas/deploy2nekoweb@v1.0.1
  with:
    # Your nekoweb API key.
    nekoweb-api-key: ${{ secrets.NEKOWEB_API_KEY }}
    # The nekoweb domain to deploy to.
    nekoweb-domain: https://nettown.nekoweb.org/ 
    # Your Nekoweb username. (Required for Recently Updated feature)
    nekoweb-username: nettown
    # The directory you would like to deploy.
    directory: nettown.nekoweb.org